packages:
  - 'packages/*'

catalog:
  typescript: 5.6.3
  vue: 3.5.21
  vue-router: 4.5.1
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1738'
  vitest: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1738'
  jsdom: 26.1.0
  fs-extra: ^9.0.1
  live-server: ^1.2.1
  rimraf: ^5.0.1
  tinyexec: ^0.3.0
  rattail: ^2.0.9
  vite-plus: 'https://pkg.pr.new/voidzero-dev/vite-plus@1738'
  '@types/node': ^20.19.0
  '@vitest/coverage-istanbul': 4.1.4
  '@vue/runtime-core': 3.5.21
  '@vue/compiler-sfc': 3.5.21
  '@vitejs/plugin-vue': 6.0.6
  '@vitejs/plugin-vue-jsx': 5.1.5
  '@vue/babel-plugin-jsx': 1.5.0
  '@vue/test-utils': 2.4.6

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - vite-plus
  - vite
  - vitest
  - '@voidzero-dev/*'
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
blockExoticSubdeps: false

